name: CI 

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                arch: [amd64, arm64]
                go-version: [1.24]

        steps:
          - name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: ${{ matrix.go-version }}
    
          - name: Check out code
            uses: actions/checkout@v4
    
          - name: Install dependencies
            run: go mod tidy
            working-directory: ./server
    
          - name: Run build
            run: go build
            working-directory: ./server
    
          - name: Run tests
            run: go test ./...
            working-directory: ./server